name: "Collect PWA Data"

on:
  schedule:
    # Run every day at 6:00 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/collect-pwa-data.yml"

permissions:
  contents: write
  pages: read

jobs:
  collect-pwa-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Collect PWA data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: pwabucket
        run: node scripts/generate-pwa-data.js

      - name: Commit and push changes
        run: ./scripts/commit-and-push.sh

      - name: Upload PWA data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pwa-data
          path: public/data/pwa-data.json
          retention-days: 30
